# Cron schedule must be valid
jobs:
  - name: event_lambda_trigger_0
    schedule: 'cron(*/1 * * * ? *)'
  - name: event_lambda_trigger_1
    schedule: 'cron(*/1 * * * ? *)'
  - name: event_lambda_trigger_2
    schedule: 'cron(*/1 * * * ? *)'