service: event

provider:
  name: aws
  region: us-west-1
  runtime: provided.al2
  environment:
    AMQP_HOST: "stomp+ssl://b-7d4aef2a-2c19-4131-90b0-18e9e14c7e12-1.mq.us-west-1.amazonaws.com:61614"
    AMQP_USERNAME: "root"
    AMQP_PASSWORD: "Admin@123456"

functions:
  lambda_function-dev:
    handler: bootstrap
    events:
      - schedule:
          name: Event
          description: health check
          rate: "cron(*/1 * * * ? *)"
          enabled: true
          input:
            jobName: Event