name: Event-Job-Scheduling

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      TF_WORKSPACE: dev  # Set your Terraform workspace name here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Golang code
        working-directory: ${{ github.workspace }}  # Set the working directory to your Golang code directory
        run: |
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          go build -o bootstrap main.go
          
      - name: Get Credentionals
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1                 # Same with the lambda function region

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Deploy Serverless Service
        working-directory: ${{ github.workspace }}
        run: |
          sls deploy --verbose

      # - name: Update CloudWatch Events Rule
      #   run: |
      #     aws events put-rule --name event_lambda_trigger --schedule-expression "cron(*/5 * * * ? *)"
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
